### ISSUE TITLE
where is the create_prompts function mentioned in the main_prefix_gpt2.py

### ISSUE THREAD

**Issue by huangfu170** [yangkexin/Tailor#3]
Congratulations on your article being accepted by ACL. I have noticed your work in 2022, arxiv. After downloading your code. I found that there seems some functions missing, such as the `from utils import create_prompts, post_process_sents` in main_prefix_gpt2.py. Is there something wrong or I ignored some important file? Any reply will help.

**Comment by lihaoling** [comment]
+1

**Comment by ghost** [comment]
+1

**Comment by drmoody1999** [comment]
+1

**Comment by yangkexin** [comment]
Sorry for the missing, please see the new utils.py
